### ISSUE TITLE
Segmentation fault after tests run with -O0

### ISSUE THREAD

**Issue by anb0s** [vdksoft/signals#8]
If vdksignals tests are compiled with MinGW GCC 9.2 without optimization (-O0 e.g. for GCOV etc.) the tests run is PASSED:

```
[ RUN      ] SignalsTest/0.SignalSelfDestruction
[       OK ] SignalsTest/0.SignalSelfDestruction (0 ms)
[ RUN      ] SignalsTest/0.CompareFunctions
[       OK ] SignalsTest/0.CompareFunctions (0 ms)
[ RUN      ] SignalsTest/0.CompareMethods
[       OK ] SignalsTest/0.CompareMethods (0 ms)
[ RUN      ] SignalsTest/0.Functor
[       OK ] SignalsTest/0.Functor (0 ms)
[ RUN      ] SignalsTest/0.ConnectDisconnectEqualSlotsByOne
[       OK ] SignalsTest/0.ConnectDisconnectEqualSlotsByOne (0 ms)
[----------] 21 tests from SignalsTest/0 (94 ms total)

[----------] Global test environment tear-down
[==========] 46 tests from 3 test suites ran. (94 ms total)
[  PASSED  ] 46 tests.
Result: -1073741819

```
but it shows a segmentation fault:
```
Thread #1 0 (Suspended : Signal : SIGSEGV:Segmentation fault)	
	std::__atomic_base<unsigned long long>::operator--() at atomic_base.h:327 0x53328a	
	vdk::internal::signals::connection::decr_refs() at signals.cpp:442 0x48fa9c	
	vdk::internal::signals::command::~command() at signals.cpp:989 0x402e9c	
	vdk::internal::signals::memory_delete<vdk::internal::signals::command>() at signals.h:88 0x4924b5	
	vdk::internal::signals::channel::close() at signals.cpp:260 0x401a78	
	vdk::internal::signals::this_thread_channel()::channel_owner::~channel_owner at signals.cpp:285 0x59c6fb	
	run_dtor_list() at cxa_atexit.c:59 0x45871e	
	tls_callback() at cxa_atexit.c:131 0x4587d4	
	0x7ffe6f3b8f07	

```
![image](https://user-images.githubusercontent.com/95811/70046568-98d49d00-15c6-11ea-80d4-6b4050f13acd.png)

Do you have an idea why `__atomic_add_fetch` can crash?

**Comment by vdksoft** [comment]
I will look into this problem as soon as I can. I didn't have seg faults using signals and the problem seems very nasty.

**Comment by anb0s** [comment]
Thanks!,

I've tested this with MSYS2 environment (MinGW 64 GCC 9.2, GDB 8.3.1, cmake 3.15) and see same error.

Configure and Build as DEBUG:
`cmake -DCMAKE_BUILD_TYPE=DEBUG  -DCMAKE_C_FLAGS_DEBUG="-g -O0" -DCMAKE_CXX_FLAGS_DEBUG="-g -O0" -B _build/ -S .`

`cmake --build _build/`

Run GDB:
`gdb _build/tests/signals-test.exe`
`> run`

Same error showed:
```
[----------] Global test environment tear-down
[==========] 46 tests from 3 test suites ran. (344 ms total)
[  PASSED  ] 46 tests.
pure virtual method called
terminate called without an active exception
[Thread 20524.0x4b44 exited with code 3]
[Thread 20524.0xf38 exited with code 3]
[Thread 20524.0x1cd4 exited with code 3]
[Thread 20524.0x3a74 exited with code 3]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000049115a in std::__atomic_base<unsigned long long>::operator-- (this=0x28) at D:/msys64/mingw64/include/c++/9.2.0/bits/atomic_base.h:327
327           { return __atomic_sub_fetch(&_M_i, 1, int(memory_order_seq_cst)); }
```

**Comment by vdksoft** [comment]
This problem drives me mad. I've spent some time on it and I was able to reproduce it. Here is what I've managed to find out so far.
The seg fault happens only when compiled on MinGW. It does not happen on Linux gcc, clang and Visual Studio compilers. Moreover, it seems the problem is not with the signals library itself. If you try to compile even this simple program, you will get similar seg fault.

```
std::shared_ptr<int> function()
{
    thread_local std::shared_ptr<int> ptr{ new int{ 10 } };
    return ptr;
}

int main()
{
    std::thread th{ []()
    {
        auto ptr = function();
    } };

    auto ptr = function();

    th.join();

    return 0;
}
```
The idea here is that function creates and returns a shared_ptr that is associated with the thread that called the function. So, each thread that calls the function must have its own instance of shared_ptr. If you compile it, for example, as:
`g++ -O0 -g -pthread -o main main.cpp`
and run with gdb, you will get similar seg fault.

Maybe I am missing something, but I can't see how this simple program violates any rules of the C++ standard. So, probably, it has something to do with thread_local storage variables on MinGW. I am not that familiar with MinGW, but I would like to get to the bottom of this, since such seg faults are very annoying for me.

**Comment by anb0s** [comment]
Yes it's not related to vdk-signals. I cannot reproduce this at linux with CCG and Clang. So it must somehow be related to the MinGW environment. I'm also not that familiar with MinGW, but the company i'm working for uses Windows as main dev system with MSYS2 / MinGW environment for generic targets and unit-testing with googletest etc.

I will also try to dive into MinGW and report if i find something.

Anyway Thank You for the support!

P.S.: you can close this issue as not related to vdk-signals

**Comment by vdksoft** [comment]
I did a little bit more digging on the issue.
Yes, it seems like something is wrong with thread_local variables in MinGW. Signals use thread_local variables internally (roughly similar to the code I wrote above), and this is exactly the place where the problem occurs.
